## Project Stage - II (Data Modeling and Hypothesis Testing)

## Number of cases Analysis  - Read the dataset

In [1]:
import pandas as pd
covid_19_cases = pd.read_csv('../../../data/stage_2/covid_confirmed_usafacts.csv')
covid_19_cases

,countyFIPS,County Name,State,StateFIPS,2020-01-22,2020-01-23,2020-01-24,2020-01-25,2020-01-26,2020-01-27,...,2021-08-07,2021-08-08,2021-08-09,2021-08-10,2021-08-11,2021-08-12,2021-08-13,2021-08-14,2021-08-15,2021-08-16
0,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1001,Autauga County,AL,1,0,0,0,0,0,0,...,7694,7694,7788,7818,7854,7890,7931,7931,7931,8061
2,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,26822,26822,27477,27736,28020,28358,28629,28629,28629,29234
3,1005,Barbour County,AL,1,0,0,0,0,0,0,...,2585,2585,2629,2649,2681,2699,2732,2732,2732,2761
4,1007,Bibb County,AL,1,0,0,0,0,0,0,...,2973,2973,3016,3034,3056,3069,3095,3095,3095,3129
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,56037,Sweetwater County,WY,56,0,0,0,0,0,0,...,5056,5056,5056,5090,5090,5108,5114,5127,5127,5127
3189,56039,Teton County,WY,56,0,0,0,0,0,0,...,3960,3960,3960,4003,4003,4014,4044,4068,4068,4068
3190,56041,Uinta County,WY,56,0,0,0,0,0,0,...,2498,2498,2498,2538,2538,2543,2559,2593,2593,2593
3191,56043,Washakie County,WY,56,0,0,0,0,0,0,...,950,950,950,958,958,960,968,967,967,967
3192,56045,Weston County,WY,56,0,0,0,0,0,0,...,694,694,694,699,699,700,700,705,705,705

In [2]:
# We have statewide unallocated for every State and countyFIPS is filled with 0 and it repeats for every Country. 
# let's clean up the dataset by removing those rows since we cannot access them uniquely for a state
dummyvalues = covid_19_cases.index[covid_19_cases['countyFIPS'] == 0].tolist()
covid_19_cases = covid_19_cases.drop(labels=dummyvalues,axis=0)

In [3]:
covid_19_cases

,countyFIPS,County Name,State,StateFIPS,2020-01-22,2020-01-23,2020-01-24,2020-01-25,2020-01-26,2020-01-27,...,2021-08-07,2021-08-08,2021-08-09,2021-08-10,2021-08-11,2021-08-12,2021-08-13,2021-08-14,2021-08-15,2021-08-16
1,1001,Autauga County,AL,1,0,0,0,0,0,0,...,7694,7694,7788,7818,7854,7890,7931,7931,7931,8061
2,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,26822,26822,27477,27736,28020,28358,28629,28629,28629,29234
3,1005,Barbour County,AL,1,0,0,0,0,0,0,...,2585,2585,2629,2649,2681,2699,2732,2732,2732,2761
4,1007,Bibb County,AL,1,0,0,0,0,0,0,...,2973,2973,3016,3034,3056,3069,3095,3095,3095,3129
5,1009,Blount County,AL,1,0,0,0,0,0,0,...,7542,7542,7603,7631,7658,7696,7758,7758,7758,7833
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,56037,Sweetwater County,WY,56,0,0,0,0,0,0,...,5056,5056,5056,5090,5090,5108,5114,5127,5127,5127
3189,56039,Teton County,WY,56,0,0,0,0,0,0,...,3960,3960,3960,4003,4003,4014,4044,4068,4068,4068
3190,56041,Uinta County,WY,56,0,0,0,0,0,0,...,2498,2498,2498,2538,2538,2543,2559,2593,2593,2593
3191,56043,Washakie County,WY,56,0,0,0,0,0,0,...,950,950,950,958,958,960,968,967,967,967
3192,56045,Weston County,WY,56,0,0,0,0,0,0,...,694,694,694,699,699,700,700,705,705,705

In [4]:
#Resetting the index to below columns so that they don't get summed up
refined_data = covid_19_cases.set_index(['countyFIPS','County Name','State','StateFIPS'])
refined_data

,,,,2020-01-22,2020-01-23,2020-01-24,2020-01-25,2020-01-26,2020-01-27,2020-01-28,2020-01-29,2020-01-30,2020-01-31,...,2021-08-07,2021-08-08,2021-08-09,2021-08-10,2021-08-11,2021-08-12,2021-08-13,2021-08-14,2021-08-15,2021-08-16
countyFIPS,County Name,State,StateFIPS,,,,,,,,,,,,,,,,,,,,,
1001,Autauga County,AL,1,0,0,0,0,0,0,0,0,0,0,...,7694,7694,7788,7818,7854,7890,7931,7931,7931,8061
1003,Baldwin County,AL,1,0,0,0,0,0,0,0,0,0,0,...,26822,26822,27477,27736,28020,28358,28629,28629,28629,29234
1005,Barbour County,AL,1,0,0,0,0,0,0,0,0,0,0,...,2585,2585,2629,2649,2681,2699,2732,2732,2732,2761
1007,Bibb County,AL,1,0,0,0,0,0,0,0,0,0,0,...,2973,2973,3016,3034,3056,3069,3095,3095,3095,3129
1009,Blount County,AL,1,0,0,0,0,0,0,0,0,0,0,...,7542,7542,7603,7631,7658,7696,7758,7758,7758,7833
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56037,Sweetwater County,WY,56,0,0,0,0,0,0,0,0,0,0,...,5056,5056,5056,5090,5090,5108,5114,5127,5127,5127
56039,Teton County,WY,56,0,0,0,0,0,0,0,0,0,0,...,3960,3960,3960,4003,4003,4014,4044,4068,4068,4068
56041,Uinta County,WY,56,0,0,0,0,0,0,0,0,0,0,...,2498,2498,2498,2538,2538,2543,2559,2593,2593,2593
56043,Washakie County,WY,56,0,0,0,0,0,0,0,0,0,0,...,950,950,950,958,958,960,968,967,967,967
56045,Weston County,WY,56,0,0,0,0,0,0,0,0,0,0,...,694,694,694,699,699,700,700,705,705,705

## Total number of cases per day

In [5]:
# Generate total number of covid cases per day in the United States
covid_cases_summed = refined_data.sum(axis = 1, skipna = True)
covid_cases_summed

countyFIPS  County Name         State  StateFIPS
1001        Autauga County      AL     1            1884413
1003        Baldwin County      AL     1            5871582
1005        Barbour County      AL     1             679697
1007        Bibb County         AL     1             730198
1009        Blount County       AL     1            1829087
                                                     ...
56037       Sweetwater County   WY     56           1105054
56039       Teton County        WY     56            962290
56041       Uinta County        WY     56            597900
56043       Washakie County     WY     56            246430
56045       Weston County       WY     56            172430
Length: 3142, dtype: int64

In [6]:
new_covid_dataframe = pd.DataFrame(columns=refined_data.columns)
new_covid_dataframe = new_covid_dataframe.append(covid_cases_summed, ignore_index=True)

TypeError: Expected tuple, got str

## Number of cases per day after calculating difference from previous day with current day

In [ ]:
newcases_perday = new_covid_dataframe.diff(axis=1)
newcases_perday

In [ ]:
newcases_perday.drop(columns=['2020-01-22'], inplace=True)
newcases_perday

## Calculate the total number of weeks for the dataset

In [ ]:
import math
number_of_weeks = math.floor(len(covid_cases_summed)/7)
number_of_weeks

## Total number of cases every week

In [ ]:
# This function calculates the total number of cases and average cases occured every week based on the operation value recieved
def calculate_sum_avg(dataset,operation):
    weekly_data = []
    i=0
    counter=7
    x=0
    while (x<number_of_weeks):
        if(operation == "sum"):
            batch = dataset.iloc[:,i:counter].sum(axis=1).astype(int)
        elif (operation == "avg"):
            batch = round(dataset.iloc[:,i:counter].mean(axis=1)).astype(int)
        i = i+7
        counter = counter+7
        x = x+1
        weekly_data.append(batch)
    return weekly_data

In [ ]:
IS_SUM = "sum"
weekly_summed_data = calculate_sum_avg(newcases_perday,IS_SUM)
total_cases = pd.concat(weekly_summed_data, axis=1)
total_cases

##  Average number of cases every week

In [ ]:
IS_MEAN = "avg"
weekly_averaged_data = calculate_sum_avg(newcases_perday,IS_MEAN)
new_avg = pd.concat(weekly_averaged_data, axis=1)
new_avg

##  calculating (mean, median, mode) for number of covid cases of every week taken together.

In [ ]:
mean_all_week = round(new_avg.mean(axis=1)).astype(int)
mean_all_week

In [ ]:
median_all_week = round(new_avg.median(axis=1)).astype(int)
median_all_week

In [ ]:
mode_all_week = round(new_avg.mode(axis=1)).astype(int)
mode_all_week

## Death case Analysis

## Read the covid death cases dataset

In [ ]:
covid_19_death_cases = pd.read_csv('../../../data/stage_2/covid_deaths_usafacts.csv')
covid_19_death_cases

## Removing the Statewide unallocated values

In [ ]:
dummyvalues_death = covid_19_death_cases.index[covid_19_death_cases['countyFIPS'] == 0].tolist()
covid_19_death_cases = covid_19_death_cases.drop(labels=dummyvalues_death,axis=0)

## Resetting the indexes to countyFIPS, countyname, state and StateFIPS to avoid summing

In [ ]:
refined_data_death = covid_19_death_cases.set_index(['countyFIPS','County Name','State','StateFIPS'])
refined_data_death

## Finding total number of cases per day across all states

In [ ]:
# Generate total number of covid cases per day in the United States
covid_death_summed = refined_data_death.sum(axis = 0, skipna = True)
covid_death_summed

In [ ]:
new_covid_death_dataframe = pd.DataFrame(columns=refined_data_death.columns)
new_covid_death_dataframe = new_covid_death_dataframe.append(covid_death_summed, ignore_index=True)
new_covid_death_dataframe

In [ ]:
newdeaths_perday = new_covid_death_dataframe.diff(axis=1)
newdeaths_perday.drop(columns=['2020-01-22'], inplace=True)
newdeaths_perday

## Calculating sum of death cases per week

In [ ]:
covid_death_summed_weekely = calculate_sum_avg(newdeaths_perday, IS_SUM)

In [ ]:
total_death_cases = pd.concat(covid_death_summed_weekely, axis=1)
total_death_cases

## Calculating average death cases per week

In [ ]:
covid_death_avg = calculate_sum_avg(newdeaths_perday, IS_MEAN)

In [ ]:
weekly_avg = pd.concat(covid_death_avg, axis=1)
weekly_avg

## Finding out Mean, Median and mode for deaths due to covid19 in the United states

In [ ]:
mean_death_weekly = round(weekly_avg.mean(axis=1)).astype(int)
mean_death_weekly

In [ ]:
median_death_weekly = round(weekly_avg.median(axis=1)).astype(int)
median_death_weekly

In [ ]:
mode_death_weekly = round(weekly_avg.mode(axis=1)).astype(int)
mode_death_weekly

### Task 1 - 2 Comparing data with other countries

#### The countries that are selected for comparison are Indonesia, Brazil, Nigeria, Russia, Japan. These countries have lesser population than USA but have higher population compared to many other countries which has far more less population than US.

##### Downloaded all countries data from the ourworldindata website and reading it to the notebook.

In [ ]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

In [ ]:
import datetime
covid_world = pd.read_csv('../../../data/stage_2/owid-covid-data.csv')
covid_world

##### This dataset contain data of all countries, so selecting specific countries that we want to compare with (Indonesia, Brazil, Nigeria, Russia, Japan)

In [ ]:
covid_world = covid_world[covid_world["location"].isin(["Indonesia", "Brazil", "Nigeria", "Russia", "Japan"])]
covid_world

##### Selecting the specific data that we need from the whole dataset
##### some country values started from march, so to get data from same range of dates below date range values are chosen. Below dataframe shows each day cases and deaths for all 5 countries

In [ ]:
covid_world_data = covid_world[["location","date","new_cases","new_deaths","population"]]
covid_world_data = covid_world_data[(covid_world_data['date'] > '2020-03-10') & (covid_world_data['date'] <= '2021-08-16')]
covid_world_data

##### summing up the weekly data for each country. Below dataframe contains new cases and deaths value per week

In [ ]:
covid_weekly = covid_world_data.groupby('location').resample('W-Mon', on='date').sum().reset_index().sort_values(by=['location','date'])

In [ ]:
covid_weekly

##### Calculating per day mean value for each country (for new cases and deaths as well)

In [ ]:
world_perday_mean = covid_world_data.groupby("location")["new_cases","new_deaths"].mean().round(decimals=0)
world_perday_mean

##### Calculating Mean of every week

In [ ]:
covid_week_mean = covid_world_data.groupby('location').resample('W-Mon', on='date').mean().reset_index().sort_values(by=['location','date'])
round(covid_week_mean)

#### Calculating mean value of all weeks taken together for each country. Inserting the US mean values to this dataframe for better comparison

In [ ]:
world_weekly_mean = covid_weekly.groupby("location")["new_cases","new_deaths"].mean().round(decimals=0).reset_index()
world_weekly_mean.loc[len(world_weekly_mean.index)] = ['UnitedStates', mean_all_week[0], mean_death_weekly[0]]
world_weekly_mean

##### Calculating median value of all weeks for each country. Inserting the US median values to this dataframe for better comparison

In [ ]:
world_weekly_median = covid_weekly.groupby("location")["new_cases","new_deaths"].median().round(decimals=0).reset_index()
world_weekly_median.loc[len(world_weekly_median.index)] = ['UnitedStates', median_all_week[0], median_death_weekly[0]]
world_weekly_median

In [ ]:
# Haven't figured this out.. will change when I get this

world_weekly_mode = covid_weekly.mode()['new_cases'][0]
world_weekly_mode

##### As we can see from the above mean and median values of all countries brazil has the highest no of cases and deaths than other countries. Nigeria has the least no of cases and deaths compared to all the other countries that are taken