In [2]:
import pandas as pd

#### Reading Confirmed Cases dataset

In [11]:
confirmed_cases_dataset = pd.read_csv("../../../data/stage_1/covid_confirmed_usafacts.csv")
confirmed_cases_dataframe = pd.DataFrame(confirmed_cases_dataset)

In [12]:
confirmed_cases_dataframe

,countyFIPS,County Name,State,StateFIPS,2020-01-22,2020-01-23,2020-01-24,2020-01-25,2020-01-26,2020-01-27,...,2021-08-07,2021-08-08,2021-08-09,2021-08-10,2021-08-11,2021-08-12,2021-08-13,2021-08-14,2021-08-15,2021-08-16
0,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1001,Autauga County,AL,1,0,0,0,0,0,0,...,7694,7694,7788,7818,7854,7890,7931,7931,7931,8061
2,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,26822,26822,27477,27736,28020,28358,28629,28629,28629,29234
3,1005,Barbour County,AL,1,0,0,0,0,0,0,...,2585,2585,2629,2649,2681,2699,2732,2732,2732,2761
4,1007,Bibb County,AL,1,0,0,0,0,0,0,...,2973,2973,3016,3034,3056,3069,3095,3095,3095,3129
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,56037,Sweetwater County,WY,56,0,0,0,0,0,0,...,5056,5056,5056,5090,5090,5108,5114,5127,5127,5127
3189,56039,Teton County,WY,56,0,0,0,0,0,0,...,3960,3960,3960,4003,4003,4014,4044,4068,4068,4068
3190,56041,Uinta County,WY,56,0,0,0,0,0,0,...,2498,2498,2498,2538,2538,2543,2559,2593,2593,2593
3191,56043,Washakie County,WY,56,0,0,0,0,0,0,...,950,950,950,958,958,960,968,967,967,967
3192,56045,Weston County,WY,56,0,0,0,0,0,0,...,694,694,694,699,699,700,700,705,705,705

In [21]:
confirmed_cases_dataframe.dtypes

countyFIPS      int64
County Name    object
State          object
StateFIPS       int64
2020-01-22      int64
                ...
2021-08-12      int64
2021-08-13      int64
2021-08-14      int64
2021-08-15      int64
2021-08-16      int64
Length: 577, dtype: object

#### Reading County population Data

In [22]:
county_population_data = pd.read_csv("../../../data/stage_1/covid_county_population_usafacts.csv")
county_population_dataframe = pd.DataFrame(county_population_data)

In [23]:
county_population_dataframe

      countyFIPS            County Name State  population
0              0  Statewide Unallocated    AL           0
1           1001         Autauga County    AL       55869
2           1003         Baldwin County    AL      223234
3           1005         Barbour County    AL       24686
4           1007            Bibb County    AL       22394
...          ...                    ...   ...         ...
3190       56037      Sweetwater County    WY       42343
3191       56039           Teton County    WY       23464
3192       56041           Uinta County    WY       20226
3193       56043        Washakie County    WY        7805
3194       56045          Weston County    WY        6927

[3195 rows x 4 columns]

In [25]:
county_population_dataframe.dtypes

countyFIPS      int64
County Name    object
State          object
population      int64
dtype: object

#### Reading Covid Deaths data

In [26]:
death_facts = pd.read_csv("../../../data/stage_1/covid_deaths_usafacts.csv")
death_facts_dataframe = pd.DataFrame(death_facts)

In [27]:
death_facts_dataframe

,countyFIPS,County Name,State,StateFIPS,2020-01-22,2020-01-23,2020-01-24,2020-01-25,2020-01-26,2020-01-27,...,2021-08-07,2021-08-08,2021-08-09,2021-08-10,2021-08-11,2021-08-12,2021-08-13,2021-08-14,2021-08-15,2021-08-16
0,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1001,Autauga County,AL,1,0,0,0,0,0,0,...,114,114,114,114,114,114,114,114,114,114
2,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,330,330,330,332,338,342,344,344,344,347
3,1005,Barbour County,AL,1,0,0,0,0,0,0,...,63,63,63,63,64,64,65,65,65,65
4,1007,Bibb County,AL,1,0,0,0,0,0,0,...,66,66,66,66,67,67,67,67,67,67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,56037,Sweetwater County,WY,56,0,0,0,0,0,0,...,45,45,45,45,45,45,45,45,45,45
3189,56039,Teton County,WY,56,0,0,0,0,0,0,...,11,11,11,11,11,11,11,11,11,11
3190,56041,Uinta County,WY,56,0,0,0,0,0,0,...,14,14,14,14,14,14,14,14,14,14
3191,56043,Washakie County,WY,56,0,0,0,0,0,0,...,26,26,26,26,26,26,26,26,26,26
3192,56045,Weston County,WY,56,0,0,0,0,0,0,...,6,6,6,6,6,6,6,6,6,6

In [28]:
death_facts_dataframe.dtypes

countyFIPS      int64
County Name    object
State          object
StateFIPS       int64
2020-01-22      int64
                ...
2021-08-12      int64
2021-08-13      int64
2021-08-14      int64
2021-08-15      int64
2021-08-16      int64
Length: 577, dtype: object

#### Merging Confirmed data and Deaths data

In [29]:
merged_confirmed_deaths = pd.merge(confirmed_cases_dataframe, death_facts_dataframe, on=['countyFIPS','County Name','State','StateFIPS'])
merged_confirmed_deaths

,countyFIPS,County Name,State,StateFIPS,2020-01-22_x,2020-01-23_x,2020-01-24_x,2020-01-25_x,2020-01-26_x,2020-01-27_x,...,2021-08-07_y,2021-08-08_y,2021-08-09_y,2021-08-10_y,2021-08-11_y,2021-08-12_y,2021-08-13_y,2021-08-14_y,2021-08-15_y,2021-08-16_y
0,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1001,Autauga County,AL,1,0,0,0,0,0,0,...,114,114,114,114,114,114,114,114,114,114
2,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,330,330,330,332,338,342,344,344,344,347
3,1005,Barbour County,AL,1,0,0,0,0,0,0,...,63,63,63,63,64,64,65,65,65,65
4,1007,Bibb County,AL,1,0,0,0,0,0,0,...,66,66,66,66,67,67,67,67,67,67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,56037,Sweetwater County,WY,56,0,0,0,0,0,0,...,45,45,45,45,45,45,45,45,45,45
3189,56039,Teton County,WY,56,0,0,0,0,0,0,...,11,11,11,11,11,11,11,11,11,11
3190,56041,Uinta County,WY,56,0,0,0,0,0,0,...,14,14,14,14,14,14,14,14,14,14
3191,56043,Washakie County,WY,56,0,0,0,0,0,0,...,26,26,26,26,26,26,26,26,26,26
3192,56045,Weston County,WY,56,0,0,0,0,0,0,...,6,6,6,6,6,6,6,6,6,6

#### Merging the above dataset with County Population

In [30]:
merged_dataset = pd.merge(merged_confirmed_deaths,county_population_dataframe, on=['countyFIPS','State'])
merged_dataset

,countyFIPS,County Name_x,State,StateFIPS,2020-01-22_x,2020-01-23_x,2020-01-24_x,2020-01-25_x,2020-01-26_x,2020-01-27_x,...,2021-08-09_y,2021-08-10_y,2021-08-11_y,2021-08-12_y,2021-08-13_y,2021-08-14_y,2021-08-15_y,2021-08-16_y,County Name_y,population
0,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,Statewide Unallocated,0
1,1001,Autauga County,AL,1,0,0,0,0,0,0,...,114,114,114,114,114,114,114,114,Autauga County,55869
2,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,330,332,338,342,344,344,344,347,Baldwin County,223234
3,1005,Barbour County,AL,1,0,0,0,0,0,0,...,63,63,64,64,65,65,65,65,Barbour County,24686
4,1007,Bibb County,AL,1,0,0,0,0,0,0,...,66,66,67,67,67,67,67,67,Bibb County,22394
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,56037,Sweetwater County,WY,56,0,0,0,0,0,0,...,45,45,45,45,45,45,45,45,Sweetwater County,42343
3189,56039,Teton County,WY,56,0,0,0,0,0,0,...,11,11,11,11,11,11,11,11,Teton County,23464
3190,56041,Uinta County,WY,56,0,0,0,0,0,0,...,14,14,14,14,14,14,14,14,Uinta County,20226
3191,56043,Washakie County,WY,56,0,0,0,0,0,0,...,26,26,26,26,26,26,26,26,Washakie County,7805
3192,56045,Weston County,WY,56,0,0,0,0,0,0,...,6,6,6,6,6,6,6,6,Weston County,6927

In [31]:
merged = merged_dataset.drop(['County Name_y'],axis=1)
merged

,countyFIPS,County Name_x,State,StateFIPS,2020-01-22_x,2020-01-23_x,2020-01-24_x,2020-01-25_x,2020-01-26_x,2020-01-27_x,...,2021-08-08_y,2021-08-09_y,2021-08-10_y,2021-08-11_y,2021-08-12_y,2021-08-13_y,2021-08-14_y,2021-08-15_y,2021-08-16_y,population
0,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1001,Autauga County,AL,1,0,0,0,0,0,0,...,114,114,114,114,114,114,114,114,114,55869
2,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,330,330,332,338,342,344,344,344,347,223234
3,1005,Barbour County,AL,1,0,0,0,0,0,0,...,63,63,63,64,64,65,65,65,65,24686
4,1007,Bibb County,AL,1,0,0,0,0,0,0,...,66,66,66,67,67,67,67,67,67,22394
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,56037,Sweetwater County,WY,56,0,0,0,0,0,0,...,45,45,45,45,45,45,45,45,45,42343
3189,56039,Teton County,WY,56,0,0,0,0,0,0,...,11,11,11,11,11,11,11,11,11,23464
3190,56041,Uinta County,WY,56,0,0,0,0,0,0,...,14,14,14,14,14,14,14,14,14,20226
3191,56043,Washakie County,WY,56,0,0,0,0,0,0,...,26,26,26,26,26,26,26,26,26,7805
3192,56045,Weston County,WY,56,0,0,0,0,0,0,...,6,6,6,6,6,6,6,6,6,6927

In [32]:
merged.to_csv('../../../data/stage_1/Covid_merged_dataset.csv',index = False)